name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".editorconfig"
      - ".gitignore"
      - "README.md"
      - ".env"
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run build
